<a href="https://colab.research.google.com/github/yanimaila/Studi-Independen/blob/main/Materi/Yani_Maila_Data_Science_Basic_Statistics_New.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Nama : Yani Maila Santi

Class : JumaTec

## **REMINDER** 
Sebelum memulai pembelajaran self-learning jangan lupa berdoa ya teman-teman dan perhatikan:
1. Jika menggunakan Jupyter Notebook, silahkan pilih "File" --> "Download" --> "Download .ipynb"
2. Jika menggunakan Colab, silahkan pilih "File" --> "Save a copy in drive"

#**MODUL 1. BASIC STATISTICS**

## Tentang Libraries untuk Statistics
#### Pada modul ini akan ditampilkan beberapa library yang digunakan dalam statistik dasar beserta beberapa contoh perhitungannya.
***

####**NUMPY**
NumPy adalah library Python yang merupakan singkatan dari "Numerical Python". Library ini biasanya digunakan untuk array. Di Python, terdapat list yang dapat dimanfaatkan untuk penggunaan array, tetapi prosesnya agak lambat. NumPy bertujuan untuk menyediakan objek array yang bekerja lebih cepat dibandingkan dengan list pada Python tradisional.

####**SCIPY**
SciPy juga merupakan library Python yang free dan bersifat open-source. Library ini digunakan untuk scientific computing dan technical computing. SciPy berisi modul untuk optimasi, aljabar linier, integrasi, interpolasi, fungsi-fungsi khusus, FFT, signal dan image processing, ODE solvers dan tugas umum lainnya dalam science dan engineering.

In [1]:
#Sistem impor Kode Python dalam satu modul mendapatkan akses ke kode di modul lain dengan proses mengimpornya.
import sys

# run cell ini untuk menginstall numpy
!{sys.executable} -m pip install numpy

# run cell ini menginstall scipy
!{sys.executable} -m pip install scipy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


# **STATISTIK DESKRIPTIF**
# Objectif
***
- **Ukuran Tendensi Sentral**
     - Mean
     - Median
     - Mode

- **Ukuran Penyebaran**

     - Range
     - Quartiles and Interquartile range
     - Percentile
     - Variance
     - Standard deviation


- **Correlation v/s Causation**
- **Kurtosis**
- **Skewness**
- **Eigen Vectors**

     

#### Membuat array sederhana dengan Numpy

In [2]:
import numpy as np

# Membuat basic array di Numpy
X=np.array([1,2,3,5,5])

## Ukuran Tendensi Sentral
***

Ukuran tendensi sentral adalah metode yang umum digunakan untuk mengidentifikasi pusat kumpulan data.
Digunakan untuk menggambarkan kumpulan data dengan mengidentifikasi posisi sentral dalam kumpulan data tersebut.

Mean, Median, dan Mode

### MEAN (Rata-rata)
***
Ukuran tendensi sentral yang paling populer. Mean disebut sebagai nilai rata-rata dalam kumpulan data. ​Didefinisikan juga sebagai jumlah semua nilai dalam kumpulan data, dibagi dengan jumlah total nilai dalam kumpulan data.
Secara matematis dapat dituliskan sebagai berikut: $ \bar X= \frac{\sum X}{n}$

In [3]:
# Mean menggunakan Numpy
print("Data",X)
print("Mean:",np.mean(X))

Data [1 2 3 5 5]
Mean: 3.2


### MEDIAN
***
Median adalah nilai tengah dari kumpulan data yang diurutkan. Jika diberikan total n nilai. Maka mediannya adalah:

1.$ \frac {(n+1)}{2} $ untuk n bernilai ganjil.


2.($\frac{n}{2}$) dan ($\frac{n}{2}+1$) untuk n bernilai genap.

In [4]:
# Mencari Median dari X
print("Data",X)
print("Median",np.median(X))

Data [1 2 3 5 5]
Median 3.0


### MODE (Modus)
***

1. Nilai yang paling sering muncul dalam kumpulan data, yaitu nilai sampel acak yang muncul dengan frekuensi terbesar.
2. Hal ini berlaku untuk semua tingkat pengukuran data, yaitu skala nominal, ordinal, interval dan rasio.

In [5]:
# Mencari Modus menggunakan numpy
print("Data",X)
vals,counts = np.unique(X, return_counts=True)
index = np.argmax(counts)
print("Mode:",vals[index])


# Mencari Modus menggunakan Scipy

from scipy import stats
print("Mode:",stats.mode(X))

Data [1 2 3 5 5]
Mode: 5
Mode: ModeResult(mode=array([5]), count=array([2]))


## Ukuran Penyebaran
***

Ukuran bagaimana data tersebar atau tersebar di sekitar rata-rata, yaitu rata- rata. Biasanya  digunakan untuk data kuantitatif, karena variabel dapat diatur dalam urutan logis dengan nilai rendah dan tinggi.

Penyebaran dapat diukur menggunakan:
1.  Range 
2.  Quartiles dan Interquartile range 
3.  Percentile
4.  Variance 
5.  Standard deviation

### RANGE
***
1. Ini adalah ukuran variabilitas yang paling sederhana.
2. Jarak antara nilai terkecil dan nilai terbesar dalam sebuah dataset.

$ Range= \max(X)-\min(X)$

In [6]:
# Menghitung Range
print("Data ",X)
print("Range ",X.max()-X.min())

Data  [1 2 3 5 5]
Range  4


### QUARTILES AND IQR (Interquartile Range)
***

1. Q1 adalah nilai "tengah" di paruh pertama kumpulan data yang diurutkan berdasarkan peringkat.
2. Q2 adalah nilai median dalam himpunan.
3. Q3 adalah nilai "tengah" di paruh kedua dari kumpulan data yang diurutkan berdasarkan peringkat.
4. Rentang interkuartil dihitung sebagai: Kuartil Atas – Kuartil Bawah.

In [7]:
# Mendefinisikan Data
data1=np.array([1, 3, 4, 5, 5, 6, 7, 11])
print("Data",data1)

# Quartile pertama (Q1)
Q1 = np.quantile(data1, .25, interpolation = 'midpoint')
print("\nQuartile 1:",Q1)
 
# Quartile kedua (Q2)
Q2 = np.quantile(data1, .50, interpolation = 'midpoint')
print("Quartile 2:",Q2)

# Quartile ketiga (Q3)
Q3 = np.quantile(data1, .75, interpolation = 'midpoint')
print("Quartile 3:",Q3)

# Rentang interQuartile(IQR)
IQR = Q3 - Q1
print("\nInterquartile Range",IQR)

Data [ 1  3  4  5  5  6  7 11]

Quartile 1: 3.5
Quartile 2: 5.0
Quartile 3: 6.5

Interquartile Range 3.0


### PERCENTILES
***

Persentiles biasanya menunjukkan bahwa persentase tertentu berada di bawah persentil itu. Misalnya, jika Anda mendapat skor di persentil ke-25, maka 25% peserta tes berada di bawah skor Anda. "25" disebut peringkat persentil.

In [8]:
print("Data",data1)
percentile_25 = np.percentile(data1,25)
print("25th Percentile:",round(percentile_25,2))

Data [ 1  3  4  5  5  6  7 11]
25th Percentile: 3.75


### VARIANCE AND STANDARD DEVIATION
***
Varians adalah ukuran seberapa tersebarnya suatu kumpulan data. Rumus varian adalah-

$\sigma^2 = \frac{\sum (X_{i}-\bar X)^2}{n-1}$

Standar Deviasi adalah akar kuadrat dari varians. Dilambangkan dengan huruf Yunani sigma $\sigma$.

In [9]:
print("Data",data1)

'''
    "Delta Degrees of Freedom": pembagi yang digunakan dalam perhitungan adalah
    ``N - ddof``, di mana ``N`` mewakili jumlah elemen. Oleh
    default `ddof` adalah nol.
'''
print("Variance:",np.var(data1,ddof=1))
print("Standard Deviation:",np.std(data1,ddof=1))

Data [ 1  3  4  5  5  6  7 11]
Variance: 8.785714285714286
Standard Deviation: 2.9640705601780613



## COVARIANCE AND CORRELATION
***

### COVARIANCE
1. Covariance adalah teknik statistik yang digunakan untuk menentukan hubungan antara pergerakan dua variabel acak. Singkatnya, berapa banyak dua variabel acak berubah bersama-sama.

2. Memberikan ukuran kekuatan korelasi antara dua atau lebih set variabel acak.

3. Contoh: Misalkan E(x) adalah nilai harapan dari suatu variabel x, dan E(y) adalah nilai harapan dari variabel y, maka kovarians antara x dan y diberikan oleh:

$cov(x, y) = E[xy] − E[x] E[y]$

- Jika COV(x, y) = 0 maka variabel tidak berkorelasi
- Jika COV(x, y) > 0 maka variabel berkorelasi positif
- Jika COV(x, y) < 0 maka variabel berkorelasi negatif

In [10]:
x = np.array([1,2,3,4,5,6,7,8,9])
print(x)
y = np.array([9,8,7,6,5,4,3,2,1])
print(y)

print("\nCovariance ",np.cov(x,y)[0,1])

[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]

Covariance  -7.5


### CORRELATION
***

1. Merupakan ukuran kekuatan hubungan antara dua variabel. Jadi, seberapa kuat dua variabel yang terhubung didefinisikan sebagai korelasi.

2. Korelasi bergantung pada dua variabelnya, dimana perubahan dalam satu variabel mempengaruhi perubahan variabel kedua.
3. Nilainya terletak pada kisaran -1 dan +1.
4. Terkait dengan kovarians dimana rumusnya adalah: $r= cov(x,y)/\sigma_x \sigma_y$, dimana r adalah koefisien korelasi Pearson.
- Koefisien korelasi yang lebih besar dari nol menunjukkan hubungan yang positif sedangkan nilai yang lebih kecil dari nol menunjukkan hubungan yang negatif.
- Nilai nol menunjukkan tidak ada hubungan antara dua variabel yang dibandingkan.

In [11]:
# Nilai matriks koefisien korelasi
print(np.corrcoef(x,y))

[[ 1. -1.]
 [-1.  1.]]


### KURTOSIS
***

1. Mengukur seberapa tinggi dan tajam puncak pusat, relatif terhadap kurva lonceng standar.
2. Juga disebut sebagai ukuran keberpihakan dari suatu distribusi data.

In [12]:
data2=np.linspace(-5,5,100)
print("Kurtosis",stats.kurtosis(data2))

Kurtosis -1.2002400240024003


### SKEWNESS
***
Besarnya dan arah kemiringan dalam distribusi data, yaitu penyimpangan dari simetri horizontal. Berikut ini adalah contoh menemukan skewness.

In [13]:
from IPython.display import HTML
from IPython.display import display

#Diambil dari link https://stackoverflow.com/questions/31517194/how-to-hide-one-specific-cell-input-or-output-in-ipython-notebook
tag = HTML('''<script>
code_show=true; 
function code_toggle() {
    if (code_show){
        $('div.cell.code_cell.rendered.selected div.input').hide();
    } else {
        $('div.cell.code_cell.rendered.selected div.input').show();
    }
    code_show = !code_show
} 
$( document ).ready(code_toggle);
</script>
To show/hide this cell's raw code input, click <a href="javascript:code_toggle()">here</a>.''')
display(tag)



from scipy.stats import skewnorm
import matplotlib.pyplot as plt

numValues = 10000
maxValue = 100
skewness = -5   #Nilai negatif merupakan left skewed, nilai positif adalah right skewed.

random = skewnorm.rvs(a = skewness,loc=maxValue, size=numValues)  #fungsi Skewnorm

random = random - min(random)      #Mengubah set random menjadi nilai minimum yang sama dengan 0.
random = random / max(random)      #Melakukan standarisasi nilai antara 0 dan 1. 
random = random * maxValue         #Mengalikan nilai standarisasi dengan nilai maximum.

#Plot histogram untuk mengecek skewness
plt.hist(random,30,density=True, color = 'red', alpha=0.1)
plt.show()

In [14]:
print("Skewness",stats.skew(data2))

Skewness -2.8663736585314984e-17


### Eigen Vector
***

Misalkan A adalah matriks nXn (Square Matrix/Matriks Persegi).

1. Vektor eigen dari A adalah vektor bukan nol v pada Rn sedemikian sehingga Av=λv, untuk beberapa skalar λ .
2. Nilai eigen dari A adalah skalar sehingga persamaan Av=λv memiliki solusi non-trivial.

Jika Av=λv untuk v tidak sama dengan 0, kita katakan bahwa adalah nilai eigen untuk v, dan v adalah vektor aneigen untuk λ .

Sebuah prefix Jerman yaitu "eigen" secara kasar diterjemahkan menjadi "(self)diri" atau "(own)milik". Vektor eigen dari A adalah vektor yang diambil ke kelipatannya dengan mentransformasi matriks T(x)=Ax, yang mungkin menjelaskan terminologi tersebut. Di sisi lain, "eigen" sering diterjemahkan sebagai "karakteristik"; kita mungkin menganggap vektor eigen sebagai menggambarkan sifat intrinsik, atau karakteristik, dari A.

Catatan-Nilai eigen dan vektor eigen hanya untuk matriks persegi.

In [15]:
import numpy as np
x = np.matrix([[4,2,3],[6,7,5],[3,6,1]])
x


matrix([[4, 2, 3],
        [6, 7, 5],
        [3, 6, 1]])

In [16]:
e = np.eye(3)
e

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
#Membuat matriks baru yang merupakan transformasi linier dari x
m = x + 45*e
#Menghitung nilai eigen dan vector eigen dari array persegi
np.linalg.eig(x) 

(array([12.76222365,  1.17374428, -1.93596793]),
 matrix([[-0.35090794, -0.78464131, -0.36647301],
         [-0.79489403,  0.40589024, -0.25466269],
         [-0.49498192,  0.4686055 ,  0.89489913]]))

In [18]:
np.linalg.eig(m)

(array([57.76222365, 46.17374428, 43.06403207]),
 matrix([[-0.35090794, -0.78464131, -0.36647301],
         [-0.79489403,  0.40589024, -0.25466269],
         [-0.49498192,  0.4686055 ,  0.89489913]]))

<br><br>
# **STATISTIK INFERENSIAL**
## Objective
***
- **Hypothesis testing**
    - Level of significance
    - One Tail Test
    - Two-tailed test
    - p-value
    

- **Compute the test statistic**

     - z-Test
         - One sampled test
         - Two sampled test
     - t-Test
         - One sampled test
         - Two sampled test
         - Paired test

## **Hypothesis Testing**
***
Hypothesis Testing (Pengujian hipotesis) atau pengujian signifikansi adalah metode statistik untuk menguji suatu klaim atau hipotesis tentang suatu parameter dalam suatu populasi, dengan menggunakan data yang diukur dalam suatu sampel.
Pengujian Hipotesis pada dasarnya adalah asumsi yang kita buat tentang parameter populasi. Misalnya, nilai rata-rata yang diperoleh siswa adalah 60.
Langkah yang harus dilakukan dalam melakukan Hypothesis Testing adalah:

**1.Menyatakan hipotesisnya terlebih dahulu**

Terdapat dua parameter di sini: Hipotesis Null dan Hipotesis Alternatif.
Hipotesis Null mengasumsikan bahwa tidak ada hubungan antara dua variabelnya, yaitu variabel yang satu tidak berpengaruh pada variabel lain. Hipotesis Null adalah asumsi dasar yang dibuat berdasarkan domain atau pengetahuan masalah.
Hipotesis alternatif adalah hipotesis yang digunakan dalam pengujian hipotesis yang bertentangan dengan hipotesis nol.
CATATAN: Jika hipotesis nol ditolak, maka hipotesis alternatif diterima. Jika hipotesis nol tidak ditolak, maka hipotesis alternatif tidak diterima.

**2.    Menetapkan kriteria untuk sebuah keputusan**

Untuk menetapkan kriteria keputusan, perlu menyatakan tingkat signifikansi untuk suatu pengujian.
Confidence level adalah seberapa yakin kita terhadap pernyataan yang diberikan. Umumnya, tidak akan 100% (biasanya akan kurang dari 100%).

   Tingkat signifikansi:
        Mengacu pada tingkat signifikansi di mana kita menerima atau menolak hipotesis nol. Tingkat signifikansi dilambangkan dengan .
        = tingkat kepercayaan 1

   One Tail Test:

       Pengujian hipotesis statistik, di mana daerah penolakan hanya pada satu sisi dari distribusi sampling, disebut uji satu sisi.
        Contoh: Nilai rata-rata siswa <= 40

   Two-tailed test:

       Uji dua sisi adalah uji statistik di mana area kritis dari suatu distribusi adalah dua sisi dan menguji apakah sampel lebih besar atau lebih kecil dari kisaran nilai tertentu. Jika sampel yang diuji jatuh ke salah satu area kritis, hipotesis alternatif diterima, bukan hipotesis nol.
       Contoh: Nilai rata-rata siswa! = 40 siswa
   p-value:

        sebuah p value digunakan dalam pengujian hipotesis untuk membantu dalam menentukan apakah hipotesis nol diterima atau tidak. Nilai p adalah bukti yang bisa digunakan untuk menyatakan hal ini. Semakin kecil nilai p, semakin kuat bukti bahwa hipotesis nol tidak diterima.

**CATATAN: Jika nilai p kurang dari tingkat signifikansi yang dipilih maka hipotesis nol tidak diterima (ditolak) sehingga menyatakan bahwa sampel yang diberikan memiliki bukti yang mendukung hipotesis alternatif.**
<br><br><br>
**3.    Hitung statistik uji**

Ini adalah Tes yang paling banyak digunakan untuk Pengujian Hipotesis.
- Z Test
- T Test
- ANOVA Test
- Chi-Square Test

**4.    Membuat keputusan berdasarkan hasil tes.**

## **z-Test di hypothesis testing**
***

  Uji z adalah uji hipotesis dimana z-statistik mengikuti distribusi normal. Uji-z paling baik digunakan untuk sampel yang lebih besar dari 30 karena, berdasarkan teorema limit pusat, ketika jumlah sampel semakin besar, maka sampel tersebut sekiranya akam terdistribusi secara normal.
    Uji Z dilakukan jika standar deviasi diketahui.

**One Sample Z test:**
    
   Dalam satu sampel uji-z, kami memeriksa satu kelompok data dan memutuskan apakah rata-rata sampel sama dengan rata-rata populasi atau tidak.
   Tekanan darah dapat diukur dengan lengan atau jari seseorang. Dataset yang digunakan di sini memiliki dua kolom yang merupakan pembacaan tekanan darah sistolik pasien yang menggunakan kedua metode tersebut. Dua kolom diberi nama: armys, finsys.
   
  Dalam uji-z satu sampel kami menggunakan kelompok tentara dan memutuskan apakah rata-rata sampel sama dengan rata-rata populasi atau tidak.

In [19]:
import pandas as pd
from scipy import stats

url = "https://raw.githubusercontent.com/bluedataconsulting/AIMasteryProgram/main/Lab_Exercises/Module2/systolic%20blood%20pressure.csv"
df = pd.read_csv(url)

from statsmodels.stats import weightstats as stests

ztest, pval = stests.ztest(df['armsys'], value=125) #value = mean dari 'armsys' di bawah hypothesis nol
print(pval)

if pval<0.05:                                # 0.05 adalah nilai signifikasnsi(α)
    print("Mean bukan 125")
else:
    print("Mean adalah 125")

import numpy as np

0.032546442541153964
Mean bukan 125


**Kesimpulan: 
Oleh karena mean bukan 125, maka p value < 0.05 sehingga hipotesis alternatif diterima.**

**Two Sample z-test**

Dalam Two Sample z-test, kami memeriksa dua kelompok data independen dan memutuskan apakah rata-rata sampel dari dua kelompok sama atau tidak.

In [20]:
import pandas as pd
from scipy import stats

url = "https://raw.githubusercontent.com/bluedataconsulting/AIMasteryProgram/main/Lab_Exercises/Module2/systolic%20blood%20pressure.csv"
df = pd.read_csv(url)

from statsmodels.stats import weightstats as stests

ztest, pval = stests.ztest(x1=df['armsys'], x2=df['fingsys'], value=0,alternative='two-sided')
print(pval)

if pval<0.05:
  print("Mean dari two samples bukan 0")
else:
  print("Mean dari two samples adalah 0")

0.07954652069053099
Mean dari two samples adalah 0


**Kesimpulan: Oleh karena mean dari two samples adalah 0 maka pval>0.05, sehingga hypothesis null diterima.**

## **t-Test in hypothesis testing**
***

Uji-t adalah jenis statistik inferensial yang digunakan untuk menentukan apakah ada perbedaan yang signifikan antara rata-rata dua kelompok yang mungkin terkait dalam fitur tertentu.
Uji-t digunakan untuk membandingkan rata-rata dari dua kelompok yang diberikan. Sampel mengikuti distribusi Gaussian. Sebuah t-Test digunakan ketika parameter seperti standar deviasi dari populasi tidak diketahui.


 **One sample t-Test**
 
Diberikan massa sampel n=20 adalah m = 8.8, 6.6, 9.5, 11.2, 10.2, 7.4, 8.0, 9.6, 9.9, 9.0, 7.6, 7.4, 10.4, 11.1, 8.5, 10.0, 11.6, 10.7, 10.3, dan 7,0 g. Kita perlu memeriksa apakah ada perbedaan antara massa rata-rata sampel ini dan massa rata-rata semua biji = 10,0 g.

In [21]:
#One Sample t test
x = [8.8, 6.6, 9.5, 11.2, 10.2, 7.4, 8.0, 9.6, 9.9, 9.0,
     7.6, 7.4, 10.4, 11.1, 8.5, 10.0, 11.6, 10.7, 10.3, 7.0]
mu = 10
t_critical = 2.093
x_bar = np.array(x).mean()
s = np.array(x).std(ddof=1) # kurangi 1 dari N untuk mendapatkan estimasi standar deviasi sampel yang tidak bias
N = len(x)
SE = s/np.sqrt(N)
t = (x_bar - mu)/SE
print("t-statistic: ",t)

# Uji-t satu sampel juga dapat dilakukan dengan library scipy sebagai berikut:
t, p = stats.ttest_1samp(x, mu)
print("t = ", t, ", p = ", p)
if p<0.05:
    print("Reject null hypothesis")
else:
    print("Accept null hypothesis")

t-statistic:  -2.2491611580763977
t =  -2.2491611580763973 , p =  0.03655562279112415
Reject null hypothesis


**Kesimpulan: Kami menolak hipotesis nol.**

### Two sample t-test
***
 
Hipotesis Null: Tidak ada perbedaan antara rata-rata dua sampel

Hipotesis Alternatif: Ada perbedaan antara rata-rata dua sampel

Misalkan kita ambil N1 = 20 sampel dan N2 = 30 sampel dari berat biji ek

In [22]:
x1 = [10.8, 10.0, 8.2, 9.9, 11.6, 10.1, 11.3, 10.3, 10.7, 9.7, 
      7.8, 9.6, 9.7, 11.6, 10.3, 9.8, 12.3, 11.0, 10.4, 10.4]

x2 = [7.8, 7.5, 9.5, 11.7, 8.1, 8.8, 8.8, 7.7, 9.7, 7.0, 
      9.0, 9.7, 11.3, 8.7, 8.8, 10.9, 10.3, 9.6, 8.4, 6.6,
      7.2, 7.6, 11.5, 6.6, 8.6, 10.5, 8.4, 8.5, 10.2, 9.2]

t_critical = 1.677    #diberikan

X1 = len(x1)
X2 = len(x2)

t1 = X1-1
t2 = X2-1

df = t1+t2

s1 = np.std(x1,ddof=1)
s2 = np.std(x2,ddof=1)

x1_bar = np.mean(x1)
x2_bar = np.mean(x2)
sp = np.sqrt((t1*s1**2 + t2*s2**2)/df)
se = sp*np.sqrt(1/X1 + 1/X2)
t = (x2_bar - x1_bar)/(se)
print("t-statistic", t)

# NOTE: the p-value given is two-sided so the one-sided p value would be p/2
t, p_twosided = stats.ttest_ind(x2, x1, equal_var=True)
print("t = ",t, ", p_twosided = ", p_twosided, ", p_onesided =", p_twosided/2)

if p<0.05:
    print("Reject null hypothesis")
else:
    print("Accept null hypothesis")

t-statistic -3.5981947686898033
t =  -3.5981947686898033 , p_twosided =  0.0007560337478801464 , p_onesided = 0.0003780168739400732
Reject null hypothesis



**Kesimpulan: Kami menolak hipotesis nol.**


### Paired t-test
***

Uji-t sampel berpasangan juga disebut uji-t sampel dependen. Mari kita ambil contoh dari dataset tekanan darah. Kita perlu memeriksa alat sampel tekanan darah seseorang sebelum dan sesudah perawatan.

Hipotesis nol: Perbedaan rata-rata antara kedua sampel adalah 0.

Hipotesis alternatif: Perbedaan rata-rata antara dua sampel tidak 0.


In [23]:
import pandas as pd
from scipy import stats

x1 = [10.8, 10.0, 8.2, 9.9, 11.6, 10.1, 11.3, 10.3, 10.7, 9.7, 
      7.8, 9.6, 9.7, 11.6, 10.3, 9.8, 12.3, 11.0, 10.4, 10.4]

x2 = [7.8, 7.5, 9.5, 11.7, 8.1, 8.8, 8.8, 7.7, 9.7, 7.0, 
      9.0, 9.7, 11.3, 8.7, 8.8, 10.9, 10.3, 9.6, 8.4, 6.6]

ttest,pval = stats.ttest_rel(x1,x2)

if pval<0.05:
    print("reject null hypothesis")
else:
    print("accept null hypothesis")


reject null hypothesis


**Kesimpulan: Di sini, kami menolak Hipotesis Null.**

## **SEMANGAT DAN SUKSES SELALU !!! 😊💪**